print('===Desafio 2===')
dia=input('Qual é o dia que você nasceu?')
mes=input('Qual é o mes que você nasceu?')
ano=input('Qual é o ano que você nasceu?')
print('Você nasceu no dia',dia, 'de',mes, 'de', ano+'.'+ ' correto?')
